  CREATE OR REPLACE FORCE EDITIONABLE VIEW "IPS_ETL"."V_RACHUNEK_DEKRETY_OPERACJE" ("NRB", "DATA_DANYCH", "ID_ANALITYKI", "ID_DEKRETU", "ID_DK_DEF", "MODULO", "KONTO", "KWOTA_MA", "KWOTA_WN", "TRESC", "NR_BANKU", "NR_DEKR", "TYP_DEKR", "DATA_OPERACJI", "NR_BANKU_ZLEC", "NR_RACHUNKU_WN", "NR_RACHUNKU_ZLEC", "NAZWA_ADR_ZLEC", "NR_BANKU_BENEF", "NR_RACHUNKU_MA", "NR_RACHUNKU_BENEF", "NAZWA_ADR_BENEF", "TYTUL_OPERACJI", "INSTRUKCJE_MIEDZYBANK", "KWOTA_OPERACJI", "KOD_WALUTY", "TYP_STRONA_OPERACJI") AS 
  SELECT
     "NRB",
     "DATA_DANYCH",
     "ID_ANALITYKI",
     "ID_DEKRETU",
     "ID_DK_DEF",
     "MODULO",
     "KONTO",
     "KWOTA_MA",
     "KWOTA_WN",
     "TRESC",
     "NR_BANKU",
     "NR_DEKR",
     "TYP_DEKR",
     "DATA_OPERACJI",
     "NR_BANKU_ZLEC",
     "NR_RACHUNKU_WN",
     "NR_RACHUNKU_ZLEC",
     "NAZWA_ADR_ZLEC",
     "NR_BANKU_BENEF",
     "NR_RACHUNKU_MA",
     "NR_RACHUNKU_BENEF",
     "NAZWA_ADR_BENEF",
     "TYTUL_OPERACJI",
     "INSTRUKCJE_MIEDZYBANK",
     "KWOTA_OPERACJI",
     "KOD_WALUTY",
     case 
     when "KWOTA_MA"=0 and "KWOTA_WN">0 then 'D'
     when "KWOTA_WN"=0 and "KWOTA_MA">0 then 'C'
     else '0'
    END AS TYP_STRONA_OPERACJI
 FROM
     ips_etl.rachunek_dekrety_operacje;