ALTER USER WKFS_STG GRANT CONNECT THROUGH BBOROWIK;     -- DAWANIE PROXY USERA DO WKFS_STG UZYTKOWNIKOWI BBOROWIK

grant execute on IPS_ETL.LADUJ_OPERACJE_NA_RACHUNKU to raporty_bps;   -- ZEZWOLENIE NA WYKONANIE PROCEDURY DLA U¯YTKOWNIKA RAPORTY_BPS

ALTER USER IVOLCHANSKA IDENTIFIED BY WkIGGEHk;  -- ZMIANA HAS£A U¯YTKOWNIKA

SELECT * FROM DBA_USERS where username = 'IVOLCHANSKA' --SPRAWDZANIE CZY U¯YTKOWNIK NIE ZABLOKOWANY

ALTER USER IVOLCHANSKA ACCOUNT UNLOCK; --ODBLOKOWANIE U¯YTKOWNIKA

GRANT CZYTELNIK_COREP TO KWYSOCKA; --DADANIE ROLI DLA U¯YTKOWNIKA

GRANT SELECT ON HURT.DEKRETY TO IPS_ETL --DODANIE UPRAWNIEN NA SELECT DO TABELI DLA U¯YTKOWNIKA IPS_ETL

grant SELECT on ext_visiona.cmg_krt_ods_20230131 to COGNOS with grant option; --DODANIE UPRAWNIEN NA SELECT DO TABELI DLA U¯YTKOWNIKA COGNOS z opcj¹ tworzenia widoku n apodstawie tej tabeli

GRANT CREATE ANY DIRECTORY TO bborowik -- --DODANIE UPRAWNIEN do tworzenia scie¿ek